---
- name: Generate SSH keys
  shell: ssh-keygen -b 2048 -t rsa -f /root/.ssh/id_rsa -q -N ""
  args:
    creates: /root/.ssh/id_rsa

- name: Update authorized_keys
  shell: cat /root/.ssh/id_rsa.pub  >> /root/.ssh/authorized_keys
