---
- name: create prometheus directory structure
  file: >
    state=directory
    path={{ item }}
    owner=root
    group=root
  with_items:
    - "{{ prometheus_root_dir }}"
    - "{{ prometheus_dist_dir }}"
    - "{{ prometheus_config_dir }}"

- stat: path={{ prometheus_dist_dir}}/prometheus-{{prometheus_version}}.linux-amd64.tar.gz
  register: prometheus_tar_gz

- name: Download prometheus tar.gz
  raw: >
    cd {{ prometheus_dist_dir }};
    wget https://github.com/prometheus/prometheus/releases/download/{{prometheus_version}}/prometheus-{{prometheus_version}}.linux-amd64.tar.gz;
  when: prometheus_tar_gz.stat.exists == False

- name: Install prometheus
  raw: >
    cd {{ prometheus_dist_dir }};
    tar xfz prometheus-{{prometheus_version}}.linux-amd64.tar.gz;
    
- name: create prometheus config file
  template: src=prometheus.yml.j2 dest={{ prometheus_config_dir }}/prometheus.yml mode=0755

- name: create prometheus upstart init files
  template: >
    src={{ item }}.j2
    dest=/etc/init/{{ item }}
  with_items:
    - prometheus.conf

- name: start prometheus service
  service: name=prometheus state=started enabled=yes
#  notify:
 #    - restart prometheus
